### ISSUE TITLE
User Experience - Design enhancement

### ISSUE THREAD

**Issue by fcoutellier** [sap-labs-france/ev-dashboard#1198]
**Logging screen**

- [ ] Replace wing icon by e-mobility logo
- [ ] Move all information like connection, creation user, forget password inside the central tile use for the login (standard for UI interface such as FB, Google, etc.)

**New dashboard screen**
- [ ]  Change the icon from blue background to white background to reduce the whole blue dominance. We keep the icon background, but we switch the background of cards to white
- [ ] The button should be moved from the up right side to the up center part (below "All sites").
- [ ] Put more white on the Dashboard that is well accepted by End User for cards only.

**Charging Stations**
- [ ] Status column -> Removed disconnected
- [ ] Status column -> Change icon from heart to cable connected or disconnected

**Statistic screen**
- [ ] Remove scroll bar from the screen
- [ ]  Keep the filter context when switching from a tab to another (existing issue already)
- [ ] Change the Pricing icon

**User screen**
- [ ] Remove ID column or hide it to a debug mode/advanced mode (cf. enable/disable debug mode button)

**Settings screen**
- [ ]  In case of inactive plugin such as billing we should add a big background image "inactive"
- [ ]  Add the email to the admin to get the plugin enable. This email must come from the Master Tenant

**Organization screen**
- [ ] In addition to the existing table, add a map with the location in dot red points view. Both view must be available by using a switch button or similar.
- [ ] Hide latitude and longitude and add a logo and little map such as displayed in google when looking for SAP Mougins.

**Charging Station screen**
- [ ] In addition to the existing table, add a map with the location in dot red points view. Both view must be available by using a switch button or similar. 

**General screen**
- [ ] Version should be hidden as tech data and not relevant for End User
