### ISSUE TITLE
Charging Profiles

### ISSUE THREAD

**Issue by LucasBrazi06** [sap-labs-france/ev-dashboard#939]
List of Charging Plans (New tab before "In Error" tab)

**Columns**
- [ ]  Charging Plan name
- [ ]  Charging station ID
- [ ]  Connector ID
- [ ]  Current connector limitation (kW/A)
- [ ]  Site area name (if component Organization is active)
- [ ]  Current site area limitation (W/A)

**Details**
- [ ] Show the Charging Plan List/Chart component
- [ ]  Add new button "Edit Site Area"
- [ ]  If Smart Charging is active:
   - [ ]  Remove static limitation tab if Smart Charging is active
   - [ ]  Charging Plan:
      - [ ]  Show the current Charging Plan List/Chart component with switch button (chart is displayed by default)
      - [ ]  Hide input fields: Temporary plan, Start date, Apply and Delete buttons
      - [ ]  Auto-refresh on list
   - [ ]  Charging plan should be given a name
   - [ ]  Add field to display the next time the optimizer batch will be triggered or timer (eg. Next Smart Charging will run in … mins).
- [ ]  If Smart Charging is NOT active:
   - [ ]  Name of the charging plan
   - [ ]  Auto-refresh on list and on charging plans drop down

**Miscs**
- [ ] If existing temporary plan is in the past, show a message: your plan is no longer valid
- [ ] Enter hours in duration in addition to mins (find a solution first, to be validated)
- [ ] Add checkbox to use the charging station’s timezone and change the schedules accordingly
- [ ] Add a row action More button (+ icon) in the list to add above or below the current record a new Schedule
- [ ] Set the focus into the Duration input field + Select all the content when new line is added so the user has just to enter the value
- [ ] Highlight the entire row in the list (background color) of the current schedule execution
